---

# <center>Introdução à Algebra Linear</center>

---

## Definição de Matriz Real  🐈

Uma matriz real $A$ de ordem $mXn$ (m por n) é uma tabela de $m.n$ números reais, dispostos em $m$ linhas e $n$ colunas, onde $m$ e $n$ são números inteiros positivos.

Uma matriz real de $m$ linhas e $n$ colunas pode ser representada por $A_{mxn}(R)$. usaremos a notação $A_{mxn}$, que se lê "matriz $A$ $m$ por $n$". Também podemos escrever $A = (a_{ij})$, onde $i \in \left\{1, 2, ..., m \right\}$ é o índice de linha e $j \in \left\{1, 2, ..., n \right\}$ é o índice de coluna, ou ainda:

<center><img src="https://beduka.com/blog/wp-content/uploads/2019/08/matriz.jpg" width=60%></center>

**Matriz com Numpy**

In [1]:
import numpy as np

In [2]:
# Matriz 3x4 (3-linhas, 4-colunas)
A_3x4 = np.array([
    [2.2, 3.0, 4.0, 5.3],
    [3.1, 1.9, 1.1, 3.3],
    [1.0, 2.2, 3.2, 2.3]
])

# Imprimindo a matriz de ordem 3 por 4 criada acima
A_3x4

array([[2.2, 3. , 4. , 5.3],
       [3.1, 1.9, 1.1, 3.3],
       [1. , 2.2, 3.2, 2.3]])

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Podemos também representar os elementos de uma matriz por fórmulas, como ilustrado no exemplo abaixo: </p><br>

In [12]:
# Definindo um array vazio
A_2x3 = np.empty([2, 3])

# Preenchendo o Array com a fórmula mostrado na imagem acima
for i in range(2):
    for j in range(3):
        if i == j:
            A_2x3[i, j] = (i+1) ** 2
        elif i != j:
            A_2x3[i, j] = ((i + j) + 2)
            
# Imprimindo a matriz criada acima
print(A_2x3)

[[1. 3. 4.]
 [3. 4. 5.]]
