---

# <center>Tipos de Matrizes</center>

---


## Introdução  🐗

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Primeiramente definiremos os tipos de matrizes dados de acordo com o número de linhas e colunas. Seja $A_{mxn} = (a_{ij})$, esta matriz pode ser:</p>

In [2]:
import numpy as np

## Matriz Linha  🦙

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Quando $m = 1$, chamamos a matriz $A_{1xn}$ de matriz linha:</p>

#### $A = (a_1, a_2, ..., a_n)$

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">A matriz linha é denominada vetor linha (ou simplesmente, vetor).</p>

In [2]:
# Matriz linha
print(f'{np.array([[1, 2, 3]])} matriz linha')

[[1 2 3]] matriz linha


## Matriz Coluna 🦒

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Quando $n=1$, chamamos a matriz de matriz coluna.</p>

$$
A = 
\begin{pmatrix}
a_1\\
a_2\\
.      \\
.      \\
.      \\
a_m
\end{pmatrix}
$$

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">A matriz coluna pode ser denominada vetor coluna</p>

In [4]:
# Matriz coluna
matriz_coluna = np.array([[1], [2], [3], [4]])
print(f"Matriz Coluna:\n{matriz_coluna}")

Matriz Coluna:
[[1]
 [2]
 [3]
 [4]]


## Matriz Quadrada  🦔

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Chamamos de matriz quadrada a matriz que tem o número de linhas igual ao número de colunas, isto é, $m=n$:</p><br>

$$
A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} &  ... & a_{1,n} \\
a_{2,1} & a_{2,2} &  ... & a_{2,n} \\
.        & .      &   .  &  .      \\
.        & .      &   .  &  .      \\
.        & .      &   .  &  .      \\
a_{m,1} & a_{m,2} &  ... &  a_{n,n}
\end{pmatrix}
$$

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Dizemos que a matriz acima é uma matriz quadrada de ordem $n$, e escrevemos apenas $A_n$.</p>

### <strong style="color: darkblue;"> - Destacamos numa matriz quadrada $A_n = (a_{ij})$ os seguintes elementos:</strong>

- <p style="font-family: Georgia; text-align: justify; font-size: 16px;"><strong>Diagonal Principal</strong>: Formada pelos termos $a_{ii}$, ou seja, pelos termos onde os índices de linha e coluna são iguais.</p>

- <p style="font-family: Georgia; text-align: justify; font-size: 16px;"><strong>Diagonal Secundária</strong>: Formada pelos termos $a_{ij}$, onde $i+j=n+1$.</p><br><br>

<center><img src="https://estudos.rededecisao.com.br/wp-content/uploads/sites/5/2020/09/O-que-e-matriz_Imagem_9.png" width=40%></center>

<strong style="color: darkred;">Observação</strong>
<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Toda matriz quadrada $A_n$, tem obrigatoriamente uma <i>diagonal principal</i> e uma <i>diagonal secundária</i>.</p>

## Matrizes Quadradas Especiais

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Dada uma matriz quadrada $A_n = (a_{ij})$, dizemos que A é uma matriz:</p>

-  <p style="font-family: Georgia; text-align: justify; font-size: 16px;"><strong>Triangular superior</strong> quando $a_{ij} = 0$ se $i > j$, ou seja, possui todos elementos abaixo da diagonal principal nulos.</p>

$$
A = 
\begin{pmatrix}
2 & -1 &  3 & -2 \\
0 & 1  &  2 &  3 \\
0 & 0  &  9 &  1 \\
0 & 0  & -0 &  5 \\
\end{pmatrix}
$$

In [10]:
# Gerando uma matriz quadrada especial triangular superior
np.triu(np.arange(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 0, 2, 3, 4],
       [0, 0, 0, 3, 4],
       [0, 0, 0, 0, 4]])

<p style="font-family: Georgia; text-align: justify; font-size: 16px;">Dada uma matriz quadrada $A_n = (a_{ij})$, dizemos que A é uma matriz:</p>

-  <p style="font-family: Georgia; text-align: justify; font-size: 16px;"><strong>Triangular inferior</strong> quando $a_{ij} = 0$ se $i < j$, ou seja, possui todos elementos abaixo da diagonal principal nulos.</p>

$$
A = 
\begin{pmatrix}
2  &  0  &  0 &  0 \\
2  &  1  &  0 &  0 \\
-3 &  3  &  9 &  0 \\
2  & -2  & -5 &  7 \\
\end{pmatrix}
$$